# test_patients.R
# -----------------------------------------------------------------------------
# Author:            Venkata
# Date last modified: Jun 5, 2020
#
# Create test imaginary patients

library(pacman)
p_load(here, dplyr)

test_patient = vector("list", 10)
test_patient[[1]] = tibble(age_years = 60,
                           gender_male_1 = 0,
                           bmi = 35,
                           sod = 1,
                           history_of_pep = 0,
                           hx_of_recurrent_pancreatitis = 1,
                           pancreatic_sphincterotomy = 0,
                           precut_sphincterotomy = 0,
                           minor_papilla_sphincterotomy = 0,
                           failed_cannulation = 0,
                           difficult_cannulation = 0,
                           pneumatic_dilation_of_intact_biliary_sphincter = 0,
                           pancreatic_duct_injection = 0,
                           pancreatic_duct_injections_2 = 0,
                           acinarization = 0,
                           trainee_involvement = 1,
                           cholecystectomy = 0,
                           pancreo_biliary_malignancy = 0,
                           guidewire_cannulation = 0,
                           guidewire_passage_into_pancreatic_duct = 0,
                           guidewire_passage_into_pancreatic_duct_2 = 0,
                           biliary_sphincterotomy = 1,
                           aggressive_hydration = c(0, 1, 0, 0, 1),
                           indomethacin_nsaid_prophylaxis = c(0, 0, 1, 0, 1),
                           pancreatic_duct_stent_placement = c(0, 0, 0, 1, 0),
                           therapy = c("No treatment", "Aggressive hydration only", "Indomethacin only",
                                       "PD stent only", "Aggressive hydration and indomethacin"),
                           patient_id = 1)

test_patient[[2]] = tibble(age_years = 30,
                           gender_male_1 = 0,
                           bmi = 25,
                           sod = 0,
                           history_of_pep = 1,
                           hx_of_recurrent_pancreatitis = 0,
                           pancreatic_sphincterotomy = 0,
                           precut_sphincterotomy = 0,
                           minor_papilla_sphincterotomy = 0,
                           failed_cannulation = 0,
                           difficult_cannulation = 0,
                           pneumatic_dilation_of_intact_biliary_sphincter = 0,
                           pancreatic_duct_injection = 0,
                           pancreatic_duct_injections_2 = 0,
                           acinarization = 0,
                           trainee_involvement = 1,
                           cholecystectomy = 0,
                           pancreo_biliary_malignancy = 0,
                           guidewire_cannulation = 0,
                           guidewire_passage_into_pancreatic_duct = 1,
                           guidewire_passage_into_pancreatic_duct_2 = 1,
                           biliary_sphincterotomy = 0,
                           aggressive_hydration = c(0, 1, 0, 0, 1),
                           indomethacin_nsaid_prophylaxis = c(0, 0, 1, 0, 1),
                           pancreatic_duct_stent_placement = c(0, 0, 0, 1, 0),
                           therapy = c("No treatment", "Aggressive hydration only", "Indomethacin only",
                                       "PD stent only", "Aggressive hydration and indomethacin"),
                           patient_id = 2)

test_patient[[3]] = tibble(age_years = 45,
                           gender_male_1 = 0,
                           bmi = 35,
                           sod = 0,
                           history_of_pep = 0,
                           hx_of_recurrent_pancreatitis = 1,
                           pancreatic_sphincterotomy = 1,
                           precut_sphincterotomy = 0,
                           minor_papilla_sphincterotomy = 0,
                           failed_cannulation = 0,
                           difficult_cannulation = 1,
                           pneumatic_dilation_of_intact_biliary_sphincter = 0,
                           pancreatic_duct_injection = 1,
                           pancreatic_duct_injections_2 = 1,
                           acinarization = 1,
                           trainee_involvement = 1,
                           cholecystectomy = 0,
                           pancreo_biliary_malignancy = 0,
                           guidewire_cannulation = 0,
                           guidewire_passage_into_pancreatic_duct = 0,
                           guidewire_passage_into_pancreatic_duct_2 = 0,
                           biliary_sphincterotomy = 0,
                           aggressive_hydration = c(0, 1, 0, 0, 1),
                           indomethacin_nsaid_prophylaxis = c(0, 0, 1, 0, 1),
                           pancreatic_duct_stent_placement = c(0, 0, 0, 1, 0),
                           therapy = c("No treatment", "Aggressive hydration only", "Indomethacin only",
                                       "PD stent only", "Aggressive hydration and indomethacin"),
                           patient_id = 3)

test_patient[[4]] = tibble(age_years = 70,
                           gender_male_1 = 0,
                           bmi = 30,
                           sod = 0,
                           history_of_pep = 1,
                           hx_of_recurrent_pancreatitis = 1,
                           pancreatic_sphincterotomy = 0,
                           precut_sphincterotomy = 0,
                           minor_papilla_sphincterotomy = 0,
                           failed_cannulation = 0,
                           difficult_cannulation = 0,
                           pneumatic_dilation_of_intact_biliary_sphincter = 0,
                           pancreatic_duct_injection = 0,
                           pancreatic_duct_injections_2 = 0,
                           acinarization = 0,
                           trainee_involvement = 1,
                           cholecystectomy = 0,
                           pancreo_biliary_malignancy = 0,
                           guidewire_cannulation = 0,
                           guidewire_passage_into_pancreatic_duct = 1,
                           guidewire_passage_into_pancreatic_duct_2 = 1,
                           biliary_sphincterotomy = 0,
                           aggressive_hydration = c(0, 1, 0, 0, 1),
                           indomethacin_nsaid_prophylaxis = c(0, 0, 1, 0, 1),
                           pancreatic_duct_stent_placement = c(0, 0, 0, 1, 0),
                           therapy = c("No treatment", "Aggressive hydration only", "Indomethacin only",
                                       "PD stent only", "Aggressive hydration and indomethacin"),
                           patient_id = 4)

test_patient[[5]] = tibble(age_years = 30,
                           gender_male_1 = 0,
                           bmi = 30,
                           sod = 1,
                           history_of_pep = 0,
                           hx_of_recurrent_pancreatitis = 0,
                           pancreatic_sphincterotomy = 0,
                           precut_sphincterotomy = 0,
                           minor_papilla_sphincterotomy = 0,
                           failed_cannulation = 0,
                           difficult_cannulation = 0,
                           pneumatic_dilation_of_intact_biliary_sphincter = 0,
                           pancreatic_duct_injection = 0,
                           pancreatic_duct_injections_2 = 0,
                           acinarization = 0,
                           trainee_involvement = 1,
                           cholecystectomy = 0,
                           pancreo_biliary_malignancy = 0,
                           guidewire_cannulation = 0,
                           guidewire_passage_into_pancreatic_duct = 0,
                           guidewire_passage_into_pancreatic_duct_2 = 0,
                           biliary_sphincterotomy = 1,
                           aggressive_hydration = c(0, 1, 0, 0, 1),
                           indomethacin_nsaid_prophylaxis = c(0, 0, 1, 0, 1),
                           pancreatic_duct_stent_placement = c(0, 0, 0, 1, 0),
                           therapy = c("No treatment", "Aggressive hydration only", "Indomethacin only",
                                       "PD stent only", "Aggressive hydration and indomethacin"),
                           patient_id = 5)

test_patient[[6]] = tibble(age_years = 65,
                           gender_male_1 = 1,
                           bmi = 35,
                           sod = 0,
                           history_of_pep = 0,
                           hx_of_recurrent_pancreatitis = 1,
                           pancreatic_sphincterotomy = 0,
                           precut_sphincterotomy = 1,
                           minor_papilla_sphincterotomy = 0,
                           failed_cannulation = 0,
                           difficult_cannulation = 1,
                           pneumatic_dilation_of_intact_biliary_sphincter = 0,
                           pancreatic_duct_injection = 0,
                           pancreatic_duct_injections_2 = 0,
                           acinarization = 0,
                           trainee_involvement = 1,
                           cholecystectomy = 0,
                           pancreo_biliary_malignancy = 0,
                           guidewire_cannulation = 0,
                           guidewire_passage_into_pancreatic_duct = 1,
                           guidewire_passage_into_pancreatic_duct_2 = 1,
                           biliary_sphincterotomy = 1,
                           aggressive_hydration = c(0, 1, 0, 0, 1),
                           indomethacin_nsaid_prophylaxis = c(0, 0, 1, 0, 1),
                           pancreatic_duct_stent_placement = c(0, 0, 0, 1, 0),
                           therapy = c("No treatment", "Aggressive hydration only", "Indomethacin only",
                                       "PD stent only", "Aggressive hydration and indomethacin"),
                           patient_id = 6)

test_patient[[7]] = tibble(age_years = 45,
                           gender_male_1 = 0,
                           bmi = 40,
                           sod = 0,
                           history_of_pep = 0,
                           hx_of_recurrent_pancreatitis = 1,
                           pancreatic_sphincterotomy = 0,
                           precut_sphincterotomy = 0,
                           minor_papilla_sphincterotomy = 0,
                           failed_cannulation = 0,
                           difficult_cannulation = 0,
                           pneumatic_dilation_of_intact_biliary_sphincter = 0,
                           pancreatic_duct_injection = 0,
                           pancreatic_duct_injections_2 = 0,
                           acinarization = 0,
                           trainee_involvement = 0,
                           cholecystectomy = 0,
                           pancreo_biliary_malignancy = 0,
                           guidewire_cannulation = 0,
                           guidewire_passage_into_pancreatic_duct = 0,
                           guidewire_passage_into_pancreatic_duct_2 = 0,
                           biliary_sphincterotomy = 0,
                           aggressive_hydration = c(0, 1, 0, 0, 1),
                           indomethacin_nsaid_prophylaxis = c(0, 0, 1, 0, 1),
                           pancreatic_duct_stent_placement = c(0, 0, 0, 1, 0),
                           therapy = c("No treatment", "Aggressive hydration only", "Indomethacin only",
                                       "PD stent only", "Aggressive hydration and indomethacin"),
                           patient_id = 7)

test_patient[[8]] = tibble(age_years = 75,
                           gender_male_1 = 0,
                           bmi = 30,
                           sod = 0,
                           history_of_pep = 0,
                           hx_of_recurrent_pancreatitis = 0,
                           pancreatic_sphincterotomy = 0,
                           precut_sphincterotomy = 1,
                           minor_papilla_sphincterotomy = 0,
                           failed_cannulation = 0,
                           difficult_cannulation = 1,
                           pneumatic_dilation_of_intact_biliary_sphincter = 0,
                           pancreatic_duct_injection = 0,
                           pancreatic_duct_injections_2 = 0,
                           acinarization = 0,
                           trainee_involvement = 0,
                           cholecystectomy = 0,
                           pancreo_biliary_malignancy = 0,
                           guidewire_cannulation = 0,
                           guidewire_passage_into_pancreatic_duct = 0,
                           guidewire_passage_into_pancreatic_duct_2 = 0,
                           biliary_sphincterotomy = 1,
                           aggressive_hydration = c(0, 1, 0, 0, 1),
                           indomethacin_nsaid_prophylaxis = c(0, 0, 1, 0, 1),
                           pancreatic_duct_stent_placement = c(0, 0, 0, 1, 0),
                           therapy = c("No treatment", "Aggressive hydration only", "Indomethacin only",
                                       "PD stent only", "Aggressive hydration and indomethacin"),
                           patient_id = 8)

test_patient[[9]] = tibble(age_years = 20,
                           gender_male_1 = 1,
                           bmi = 30,
                           sod = 0,
                           history_of_pep = 1,
                           hx_of_recurrent_pancreatitis = 1,
                           pancreatic_sphincterotomy = 0,
                           precut_sphincterotomy = 1,
                           minor_papilla_sphincterotomy = 0,
                           failed_cannulation = 1,
                           difficult_cannulation = 0,
                           pneumatic_dilation_of_intact_biliary_sphincter = 0,
                           pancreatic_duct_injection = 0,
                           pancreatic_duct_injections_2 = 0,
                           acinarization = 0,
                           trainee_involvement = 1,
                           cholecystectomy = 0,
                           pancreo_biliary_malignancy = 0,
                           guidewire_cannulation = 0,
                           guidewire_passage_into_pancreatic_duct = 0,
                           guidewire_passage_into_pancreatic_duct_2 = 0,
                           biliary_sphincterotomy = 0,
                           aggressive_hydration = c(0, 1, 0, 0, 1),
                           indomethacin_nsaid_prophylaxis = c(0, 0, 1, 0, 1),
                           pancreatic_duct_stent_placement = c(0, 0, 0, 1, 0),
                           therapy = c("No treatment", "Aggressive hydration only", "Indomethacin only",
                                       "PD stent only", "Aggressive hydration and indomethacin"),
                           patient_id = 9)

test_patient[[10]] = tibble(age_years = 50,
                            gender_male_1 = 0,
                            bmi = 35,
                            sod = 1,
                            history_of_pep = 0,
                            hx_of_recurrent_pancreatitis = 0,
                            pancreatic_sphincterotomy = 0,
                            precut_sphincterotomy = 0,
                            minor_papilla_sphincterotomy = 0,
                            failed_cannulation = 0,
                            difficult_cannulation = 1,
                            pneumatic_dilation_of_intact_biliary_sphincter = 0,
                            pancreatic_duct_injection = 0,
                            pancreatic_duct_injections_2 = 0,
                            acinarization = 0,
                            trainee_involvement = 1,
                            cholecystectomy = 0,
                            pancreo_biliary_malignancy = 0,
                            guidewire_cannulation = 0,
                            guidewire_passage_into_pancreatic_duct = 0,
                            guidewire_passage_into_pancreatic_duct_2 = 0,
                            biliary_sphincterotomy = 1,
                            aggressive_hydration = c(0, 1, 0, 0, 1),
                            indomethacin_nsaid_prophylaxis = c(0, 0, 1, 0, 1),
                            pancreatic_duct_stent_placement = c(0, 0, 0, 1, 0),
                           therapy = c("No treatment", "Aggressive hydration only", "Indomethacin only",
                                       "PD stent only", "Aggressive hydration and indomethacin"),
                            patient_id = 10)

test_patient = bind_rows(test_patient)
saveRDS(test_patient, here("data", "test_patient.rds"))
